UISAUTCOMP-6: Fix pagination, height, and width of the result list
folio-org/stripes-authority-components pull request #10
Opened 2022-08-17 12:28 UTC by Dmytro-Melnyshyn

## Purpose
Fix pagination, height, and width of the result list described in the comments of [UIPFAUTH-3](https://issues.folio.org/browse/UIPFAUTH-3)

## Issues
[UISAUTCOMP-6](https://issues.folio.org/browse/UISAUTCOMP-6)

## Screencast

https://user-images.githubusercontent.com/77053927/185120732-07fbcbd2-9a20-4995-9b3d-05ca43639cb7.mp4

## Approach

#### TODOS and Open Questions

## Learning

## Screenshots

2022-08-18 10:57 UTC, BogdanDenis requested changes

2022-08-18 10:57 UTC, BogdanDenis commented on lib/SearchResultsList/SearchResultsList.js
> +  columnWidths: null,
Let's use `defaultColumnWidths` as default prop value, and we can remove `columnWidths || defaultColumnWidths` above

2022-08-18 10:57 UTC, BogdanDenis commented on test/jest/turn-off-warnings.js
> +  /Warning: Failed %s type: %s%s/,
We should disable all prop types warnings in tests - better to fix tests to pass all required props and have correct prop types
Created a ticket to fix tests https://issues.folio.org/browse/UISAUTCOMP-7

2022-08-19 07:11 UTC, BogdanDenis approved these changes

2022-08-19 08:44 UTC, odoniyor approved these changes

2022-08-19 19:09 UTC, merged